#!/usr/bin/env python3
"""Derive prime-agent's engine-side harness state from traces/lessons.jsonl.

WHY THIS IS A GENERATOR AND NOT A DIRECTORY OF HAND-WRITTEN FILES
-----------------------------------------------------------------
PLAN §6.1 specifies "one file per lesson under harness_engine/memories/engine/". Written by
hand, that set has the failure mode this repo already paid for twice: a lesson gets added to
`traces/lessons.jsonl` (the authoritative record, enforced by validate.py) and the injected copy
is forgotten -- silently, because a MISSING memory and a memory that was never written look
identical from the outside. Deriving it means additions cannot be forgotten, and `--check` can
prove the two sides agree.

    build_memories.py            regenerate memories/engine/ from traces/lessons.jsonl
    build_memories.py --check    re-derive and exit 1 on drift

FORMAT (PLAN §6.1): the FIRST LINE is always `[engine] <rule>`, so `/refine --global` can tell
this scope from the tb_loop one by looking at one line. `class` follows as a tag on the second
line. There is deliberately NO YAML frontmatter: prime-agent's memory format is plain markdown
and the plan chose the `[engine]` prefix as the scope marker instead.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
assert HERE.name == "harness_engine", "build_memories.py belongs in agent_harness/engine_loop/harness_engine/"

TRACES = HERE.parent / "traces" / "lessons.jsonl"
MEM_DIR = HERE / "memories" / "engine"

# The provider extension is NOT copied (PLAN §6.1 / CONVENTIONS R1): a second copy of
# `gemma4-provider.ts` is a second truth, and the drift is silent (the harness keeps working,
# just against an older endpoint definition). `extensions` is therefore a relative symlink;
# --check fails if it ever becomes a real directory, i.e. if somebody copies instead of pointing.
EXT_LINK = HERE / "extensions"
EXT_TARGET = Path("..") / ".." / "tb_loop" / "harness" / "extensions"


def load_lessons() -> list[dict]:
    if not TRACES.exists():
        raise SystemExit(f"no lessons at {TRACES}")
    rows = []
    for line in TRACES.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    if not rows:
        raise SystemExit(f"{TRACES} has no records -- refusing to write an empty memory set")
    return rows


def render(lesson: dict) -> str:
    """One lesson -> one memory file. Content is the record, not a paraphrase of it."""
    lid = lesson["lesson_id"]
    rule = lesson["rule"]
    sup = lesson.get("superseded_by")
    out = [
        f"[engine] {rule}",
        "",
        f"<!-- generated by harness_engine/build_memories.py from traces/lessons.jsonl -->",
        f"<!-- lesson_id: {lid} | class: {lesson['class']} | superseded_by: {sup or '-'} -->",
        "",
        f"**class**: `{lesson['class']}`"
        + (f"  ·  **superseded_by**: `{sup}`" if sup else ""),
        "",
        "## 為什麼（because）",
        "",
        lesson["because"],
        "",
    ]
    ce = lesson.get("counterexample_observed")
    out += ["## 反例（counterexample_observed）", "", ce if ce else "（未觀測——這條規則還沒有實際被違反的紀錄，注入的價值因此較低）", ""]
    out += ["## 適用於（applies_to）", ""]
    out += [f"- `{p}`" for p in lesson["applies_to"]]
    out += ["", "---", "", "*這份 memory 是衍生物。權威是 `agent_harness/engine_loop/traces/lessons.jsonl`；*",]
    out += ["*要改內容請改那份 record，再重跑 `build_memories.py`。手改此檔會被下一次重生蓋掉。*", ""]
    return "\n".join(out)


def desired(lessons: list[dict]) -> dict[str, str]:
    return {f"{l['lesson_id']}.md": render(l) for l in lessons}


def check_link() -> list[str]:
    problems = []
    if EXT_LINK.is_symlink():
        if not EXT_LINK.exists():
            problems.append(f"{EXT_LINK.name} is a DANGLING symlink -> {EXT_LINK.resolve()}")
    elif EXT_LINK.exists():
        problems.append(
            f"{EXT_LINK.name}/ is a REAL directory, not a pointer. The provider extension must not be "
            f"copied (two copies = two truths, and the drift is silent). Delete it and recreate the "
            f"symlink to {EXT_TARGET}."
        )
    if not (EXT_LINK.parent / EXT_TARGET).resolve().is_dir():
        problems.append(f"the symlink target does not exist: {(HERE / EXT_TARGET).resolve()}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="re-derive and exit 1 on any drift")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    lessons = load_lessons()
    want = desired(lessons)

    if args.check:
        problems = check_link()
        if not MEM_DIR.is_dir():
            problems.append(f"no memory directory at {MEM_DIR}")
        else:
            have = {p.name for p in MEM_DIR.glob("*.md")}
            for name in sorted(set(have) | set(want)):
                if name not in want:
                    problems.append(f"{name}: on disk but not in lessons.jsonl (stale memory)")
                elif name not in have:
                    problems.append(f"{name}: in lessons.jsonl but no memory file")
                elif (MEM_DIR / name).read_text(encoding="utf-8") != want[name]:
                    problems.append(f"{name}: content differs from the derived text")
        if problems:
            print(f"  [error] {len(problems)} drift(s) between memories/engine/ and lessons.jsonl:")
            for p in problems:
                print(f"    {p}")
            print("    regenerate with: python3 agent_harness/engine_loop/harness_engine/build_memories.py")
            return 1
        print(f"  memories OK: {len(want)} file(s), extensions pointer resolves, no drift")
        return 0

    MEM_DIR.mkdir(parents=True, exist_ok=True)
    # Remove memories whose lesson no longer exists, so a deleted record cannot leave an
    # injected rule behind. Deleting an ORPHAN here is safe: the authoritative record is gone.
    removed = []
    for p in sorted(MEM_DIR.glob("*.md")):
        if p.name not in want:
            p.unlink()
            removed.append(p.name)

    for name, text in sorted(want.items()):
        (MEM_DIR / name).write_text(text, encoding="utf-8")

    by_class: dict[str, int] = {}
    for l in lessons:
        by_class[l["class"]] = by_class.get(l["class"], 0) + 1

    print(f"  wrote {len(want)} memory file(s) -> {MEM_DIR.relative_to(HERE.parent.parent.parent)}")
    if removed:
        print(f"  removed {len(removed)} orphan(s): {', '.join(removed)}")
    print(f"  by class: {dict(sorted(by_class.items()))}")
    print(f"  first line of every file is `[engine] <rule>` (the scope marker /refine --global looks for)")

    for p in check_link():
        print(f"  [warn] {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
