#!/bin/bash
# cgc_replay_ci.sh — CGC Expert Cache Replay Benchmark CI Gate
#
# 設計 (2026-09-05):
#   - 通用 CI 入口, 可被 GitHub Actions / Jenkins / GitLab CI 呼叫
#   - 自動偵測環境, 跟 main branch 的 .replay_bench_baseline.json 比較
#   - 結果輸出三種格式: 人讀 (stdout) + machine (.replay_bench_report.json) + GitHub PR comment (env-gated)
#
# 環境變數:
#   CGC_CI_BASE_URL       - llama-server URL (default: http://127.0.0.1:8080/v1)
#   CGC_CI_SERVER_PID     - llama-server PID (default: 從 .replay_bench_current.json 讀)
#   CGC_CI_BASELINE_REF   - 跟誰比較 (default: origin/main, fallback: HEAD~1)
#   CGC_CI_PR_COMMENT     - 若設為 1, 印出 GitHub PR comment markdown
#   CGC_CI_SKIP_START     - 若設為 1, 假設 server 已啟動 (CI 環境由 workflow 控管)
#
# 退出碼:
#   0 = PASS
#   1 = FAIL (regression)
#   2 = ERROR (baseline 缺失 / 工具異常)
#
# 用法:
#   bash scripts/ci/cgc_replay_ci.sh

set -uo pipefail

# ---- 0. 路徑解析 ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CHECK_DIR="$REPO_ROOT/scripts/check"

BASE_URL="${CGC_CI_BASE_URL:-http://127.0.0.1:8080/v1}"
SERVER_PID="${CGC_CI_SERVER_PID:-}"
BASELINE_REF="${CGC_CI_BASELINE_REF:-}"
PR_COMMENT="${CGC_CI_PR_COMMENT:-0}"
SKIP_START="${CGC_CI_SKIP_START:-0}"

REPORT="$REPO_ROOT/.replay_bench_report.json"
CURRENT="$REPO_ROOT/.replay_bench_current.json"
BASELINE="$REPO_ROOT/.replay_bench_baseline.json"

log()  { echo "[cgc-ci] $*"; }
warn() { echo "[cgc-ci] WARN: $*" >&2; }
err()  { echo "[cgc-ci] ERROR: $*" >&2; }

log "Repo:        $REPO_ROOT"
log "Base URL:    $BASE_URL"
log "Baseline ref: ${BASELINE_REF:-<auto>}"

# ---- 1. 確認工具 ----
for tool in python3 git curl; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        err "missing required tool: $tool"
        exit 2
    fi
done

# ---- 2. 決定 baseline ref ----
if [ -z "$BASELINE_REF" ]; then
    if git -C "$REPO_ROOT" rev-parse --verify origin/main >/dev/null 2>&1; then
        BASELINE_REF="origin/main"
    elif git -C "$REPO_ROOT" rev-parse --verify main >/dev/null 2>&1; then
        BASELINE_REF="main"
    else
        BASELINE_REF="HEAD~1"
    fi
fi
log "Baseline resolved: $BASELINE_REF"

# ---- 3. 抓 baseline (從 ref 拉 .replay_bench_baseline.json) ----
BASELINE_TMP="$(mktemp -t cgc-ci-baseline.XXXXXX.json)"
if ! git -C "$REPO_ROOT" show "$BASELINE_REF:.replay_bench_baseline.json" > "$BASELINE_TMP" 2>/dev/null; then
    err "cannot fetch baseline from $BASELINE_REF:.replay_bench_baseline.json"
    warn "若這是 bootstrap (第一次設 baseline), 請先 commit 一份 .replay_bench_baseline.json"
    rm -f "$BASELINE_TMP"
    exit 2
fi
log "Baseline saved to: $BASELINE_TMP"

# ---- 4. (可選) 確認 server 活著 ----
if [ "$SKIP_START" != 1 ]; then
    if ! curl -sf "${BASE_URL%/v1}/health" >/dev/null 2>&1; then
        err "llama-server not responding at $BASE_URL"
        warn "請先啟動 server 或設 CGC_CI_SKIP_START=1 (由 workflow 控管 server 生命週期)"
        rm -f "$BASELINE_TMP"
        exit 2
    fi
fi

# ---- 5. 跑 replay benchmark (all profiles) ----
log "Running replay benchmark on all 3 profiles..."
if ! python3 "$CHECK_DIR/replay_server_profile.py" \
        --all-profiles \
        --base-url "$BASE_URL" \
        --server-pid "${SERVER_PID:-0}" \
        --bench-output "$CURRENT" 2>&1 | tail -20; then
    err "replay_server_profile.py failed"
    rm -f "$BASELINE_TMP"
    exit 2
fi

if [ ! -s "$CURRENT" ]; then
    err "replay_server_profile.py produced empty $CURRENT"
    rm -f "$BASELINE_TMP"
    exit 2
fi

# ---- 6. 跟 baseline 比較 ----
log "Comparing current vs baseline..."
if ! python3 "$CHECK_DIR/replay_bench_compare.py" \
        --current "$CURRENT" \
        --baseline "$BASELINE_TMP" \
        --reference "$CHECK_DIR/replay_bench_reference.json" \
        --report "$REPORT"; then
    rc=$?
    if [ "$rc" = 1 ]; then
        err "replay_bench_compare.py returned FAIL"
        warn "regression 數 >= 2 或 improvement 數 = 0"
        COMPARE_RC=1
    else
        err "replay_bench_compare.py error (rc=$rc)"
        COMPARE_RC=2
    fi
else
    log "replay_bench_compare.py returned PASS"
    COMPARE_RC=0
fi

# ---- 7. (可選) 印 PR comment markdown ----
if [ "$PR_COMMENT" = 1 ] && [ -f "$REPORT" ]; then
    cat <<'HEADER'
<!-- CGC replay bench (auto-generated by cgc_replay_ci.sh) -->
HEADER
    python3 -c "
import json, sys
r = json.load(open('$REPORT'))
s = r.get('summary', {})
v = s.get('verdict', '?')
agg = s.get('aggregate_status', {})
print('## CGC Replay Benchmark — ', v)
print()
print('**Reason:** ', s.get('reason', ''))
print()
print('| metric | baseline | current | status |')
print('|--------|---------:|--------:|--------|')
for k, d in agg.items():
    b = d.get('baseline')
    c = d.get('current')
    st = d.get('status', '?')
    bs = f'{b:.2f}' if isinstance(b, (int, float)) else str(b)
    cs = f'{c:.2f}' if isinstance(c, (int, float)) else str(c)
    print(f'| {k} | {bs} | {cs} | {st} |')
print()
print('<!-- /CGC replay bench -->')
"
fi

rm -f "$BASELINE_TMP"
exit $COMPARE_RC
