# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pd_service_pb2 as pd__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pd_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PDServiceStub(object):
    """============================================================================
    PD Service: KV Management + Prefix Cache + CGC Command Binding
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AllocateBlocks = channel.unary_unary(
                '/pd.PDService/AllocateBlocks',
                request_serializer=pd__service__pb2.BlockRequest.SerializeToString,
                response_deserializer=pd__service__pb2.BlockResponse.FromString,
                _registered_method=True)
        self.StorePrefixKV = channel.unary_unary(
                '/pd.PDService/StorePrefixKV',
                request_serializer=pd__service__pb2.PrefixKVRequest.SerializeToString,
                response_deserializer=pd__service__pb2.PrefixKVResponse.FromString,
                _registered_method=True)
        self.GetPrefixKV = channel.unary_unary(
                '/pd.PDService/GetPrefixKV',
                request_serializer=pd__service__pb2.PrefixRequest.SerializeToString,
                response_deserializer=pd__service__pb2.PrefixResponse.FromString,
                _registered_method=True)
        self.InvalidatePrefix = channel.unary_unary(
                '/pd.PDService/InvalidatePrefix',
                request_serializer=pd__service__pb2.PrefixInvalidateRequest.SerializeToString,
                response_deserializer=pd__service__pb2.PrefixInvalidateResponse.FromString,
                _registered_method=True)
        self.ExecuteCGCCommand = channel.unary_unary(
                '/pd.PDService/ExecuteCGCCommand',
                request_serializer=pd__service__pb2.CGCCommandRequest.SerializeToString,
                response_deserializer=pd__service__pb2.CGCCommandResponse.FromString,
                _registered_method=True)
        self.ExecuteKDAForward = channel.unary_unary(
                '/pd.PDService/ExecuteKDAForward',
                request_serializer=pd__service__pb2.KDAForwardRequest.SerializeToString,
                response_deserializer=pd__service__pb2.KDAForwardResponse.FromString,
                _registered_method=True)
        self.UpdateKDABasis = channel.unary_unary(
                '/pd.PDService/UpdateKDABasis',
                request_serializer=pd__service__pb2.KDABasisRequest.SerializeToString,
                response_deserializer=pd__service__pb2.KDABasisResponse.FromString,
                _registered_method=True)
        self.PrepareHandoff = channel.unary_unary(
                '/pd.PDService/PrepareHandoff',
                request_serializer=pd__service__pb2.HandoffPrepareRequest.SerializeToString,
                response_deserializer=pd__service__pb2.HandoffPrepareResponse.FromString,
                _registered_method=True)
        self.CommitHandoff = channel.unary_unary(
                '/pd.PDService/CommitHandoff',
                request_serializer=pd__service__pb2.HandoffCommitRequest.SerializeToString,
                response_deserializer=pd__service__pb2.HandoffCommitResponse.FromString,
                _registered_method=True)
        self.ResumeDecode = channel.unary_unary(
                '/pd.PDService/ResumeDecode',
                request_serializer=pd__service__pb2.ResumeDecodeRequest.SerializeToString,
                response_deserializer=pd__service__pb2.ResumeDecodeResponse.FromString,
                _registered_method=True)
        self.AbortHandoff = channel.unary_unary(
                '/pd.PDService/AbortHandoff',
                request_serializer=pd__service__pb2.HandoffAbortRequest.SerializeToString,
                response_deserializer=pd__service__pb2.HandoffAbortResponse.FromString,
                _registered_method=True)
        self.QuerySessionState = channel.unary_unary(
                '/pd.PDService/QuerySessionState',
                request_serializer=pd__service__pb2.SessionQueryRequest.SerializeToString,
                response_deserializer=pd__service__pb2.SessionQueryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/pd.PDService/HealthCheck',
                request_serializer=pd__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=pd__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PDServiceServicer(object):
    """============================================================================
    PD Service: KV Management + Prefix Cache + CGC Command Binding
    ============================================================================
    """

    def AllocateBlocks(self, request, context):
        """Block allocation for KV cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorePrefixKV(self, request, context):
        """Prefix KV cache operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrefixKV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidatePrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCGCCommand(self, request, context):
        """CGC Command binding (PD ↔ Worker instruction interop)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteKDAForward(self, request, context):
        """KDA specific operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKDABasis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareHandoff(self, request, context):
        """DOPD session / phase handoff (proto source only; regenerate pb2 on enable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeDecode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySessionState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Distributed health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AllocateBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateBlocks,
                    request_deserializer=pd__service__pb2.BlockRequest.FromString,
                    response_serializer=pd__service__pb2.BlockResponse.SerializeToString,
            ),
            'StorePrefixKV': grpc.unary_unary_rpc_method_handler(
                    servicer.StorePrefixKV,
                    request_deserializer=pd__service__pb2.PrefixKVRequest.FromString,
                    response_serializer=pd__service__pb2.PrefixKVResponse.SerializeToString,
            ),
            'GetPrefixKV': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrefixKV,
                    request_deserializer=pd__service__pb2.PrefixRequest.FromString,
                    response_serializer=pd__service__pb2.PrefixResponse.SerializeToString,
            ),
            'InvalidatePrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidatePrefix,
                    request_deserializer=pd__service__pb2.PrefixInvalidateRequest.FromString,
                    response_serializer=pd__service__pb2.PrefixInvalidateResponse.SerializeToString,
            ),
            'ExecuteCGCCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCGCCommand,
                    request_deserializer=pd__service__pb2.CGCCommandRequest.FromString,
                    response_serializer=pd__service__pb2.CGCCommandResponse.SerializeToString,
            ),
            'ExecuteKDAForward': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteKDAForward,
                    request_deserializer=pd__service__pb2.KDAForwardRequest.FromString,
                    response_serializer=pd__service__pb2.KDAForwardResponse.SerializeToString,
            ),
            'UpdateKDABasis': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKDABasis,
                    request_deserializer=pd__service__pb2.KDABasisRequest.FromString,
                    response_serializer=pd__service__pb2.KDABasisResponse.SerializeToString,
            ),
            'PrepareHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareHandoff,
                    request_deserializer=pd__service__pb2.HandoffPrepareRequest.FromString,
                    response_serializer=pd__service__pb2.HandoffPrepareResponse.SerializeToString,
            ),
            'CommitHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitHandoff,
                    request_deserializer=pd__service__pb2.HandoffCommitRequest.FromString,
                    response_serializer=pd__service__pb2.HandoffCommitResponse.SerializeToString,
            ),
            'ResumeDecode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeDecode,
                    request_deserializer=pd__service__pb2.ResumeDecodeRequest.FromString,
                    response_serializer=pd__service__pb2.ResumeDecodeResponse.SerializeToString,
            ),
            'AbortHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortHandoff,
                    request_deserializer=pd__service__pb2.HandoffAbortRequest.FromString,
                    response_serializer=pd__service__pb2.HandoffAbortResponse.SerializeToString,
            ),
            'QuerySessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySessionState,
                    request_deserializer=pd__service__pb2.SessionQueryRequest.FromString,
                    response_serializer=pd__service__pb2.SessionQueryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=pd__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=pd__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pd.PDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pd.PDService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PDService(object):
    """============================================================================
    PD Service: KV Management + Prefix Cache + CGC Command Binding
    ============================================================================
    """

    @staticmethod
    def AllocateBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/AllocateBlocks',
            pd__service__pb2.BlockRequest.SerializeToString,
            pd__service__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StorePrefixKV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/StorePrefixKV',
            pd__service__pb2.PrefixKVRequest.SerializeToString,
            pd__service__pb2.PrefixKVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrefixKV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/GetPrefixKV',
            pd__service__pb2.PrefixRequest.SerializeToString,
            pd__service__pb2.PrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidatePrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/InvalidatePrefix',
            pd__service__pb2.PrefixInvalidateRequest.SerializeToString,
            pd__service__pb2.PrefixInvalidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCGCCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/ExecuteCGCCommand',
            pd__service__pb2.CGCCommandRequest.SerializeToString,
            pd__service__pb2.CGCCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteKDAForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/ExecuteKDAForward',
            pd__service__pb2.KDAForwardRequest.SerializeToString,
            pd__service__pb2.KDAForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKDABasis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/UpdateKDABasis',
            pd__service__pb2.KDABasisRequest.SerializeToString,
            pd__service__pb2.KDABasisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/PrepareHandoff',
            pd__service__pb2.HandoffPrepareRequest.SerializeToString,
            pd__service__pb2.HandoffPrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/CommitHandoff',
            pd__service__pb2.HandoffCommitRequest.SerializeToString,
            pd__service__pb2.HandoffCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeDecode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/ResumeDecode',
            pd__service__pb2.ResumeDecodeRequest.SerializeToString,
            pd__service__pb2.ResumeDecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/AbortHandoff',
            pd__service__pb2.HandoffAbortRequest.SerializeToString,
            pd__service__pb2.HandoffAbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/QuerySessionState',
            pd__service__pb2.SessionQueryRequest.SerializeToString,
            pd__service__pb2.SessionQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pd.PDService/HealthCheck',
            pd__service__pb2.HealthCheckRequest.SerializeToString,
            pd__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
